export default {
  "results": [
    {
      "jobtitle": "Remote Java Engineer",
      "company": "Indeed",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Indeed",
      "date": "Wed, 30 May 2018 15:06:19 GMT",
      "snippet": "4+ years industry experience in <b>Java</b>. As the world’s number 1 job site, our mission is to help people get jobs....",
      "url": "http://www.indeed.com/viewjob?jk=28775b77cbb01462&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.362755,
      "longitude": -97.792854,
      "jobkey": "28775b77cbb01462",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX 78731",
      "formattedRelativeTime": "12 days ago",
      "stations": ""
    },
    {
      "jobtitle": "Java Software Developer",
      "company": "RSS",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Indeed",
      "date": "Fri, 08 Jun 2018 00:49:47 GMT",
      "snippet": "<b>Java</b> Software Developer*. Strong development skills in HTML, CSS, <b>Java</b>, JSP, JavaScript. Experience with enterprise web applications (specifically in developing...",
      "url": "http://www.indeed.com/viewjob?jk=68221a071b56a617&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.26715,
      "longitude": -97.74306,
      "jobkey": "68221a071b56a617",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX",
      "formattedRelativeTime": "3 days ago",
      "stations": ""
    },
    {
      "jobtitle": "Java Developer",
      "company": "DigiTek",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Indeed",
      "date": "Fri, 08 Jun 2018 21:39:23 GMT",
      "snippet": "5 years of web based <b>Java</b> Development. We have an Urgent Job Opening for *Java Developer*....",
      "url": "http://www.indeed.com/viewjob?jk=c053ce475b62481f&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.26715,
      "longitude": -97.74306,
      "jobkey": "c053ce475b62481f",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX",
      "formattedRelativeTime": "3 days ago",
      "stations": ""
    },
    {
      "jobtitle": "Java Developer",
      "company": "Numentica LLC",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Indeed",
      "date": "Fri, 08 Jun 2018 12:33:41 GMT",
      "snippet": "<b>Java</b> - Software Developer:. Strong development skills in HTML, CSS, <b>Java</b>, JSP, JavaScript. Experience with enterprise web applications (specifically in...",
      "url": "http://www.indeed.com/viewjob?jk=d03c6977b259a8d3&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.26715,
      "longitude": -97.74306,
      "jobkey": "d03c6977b259a8d3",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX",
      "formattedRelativeTime": "3 days ago",
      "stations": ""
    },
    {
      "jobtitle": "Java Developer",
      "company": "Lakhi Inc",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Indeed",
      "date": "Thu, 19 Apr 2018 23:27:10 GMT",
      "snippet": "Must have 10+ years of <b>Java</b>, Spring Boot, microservices and Test Driven Development. Must have recent, hands-on experience moving legacy applications to...",
      "url": "http://www.indeed.com/viewjob?jk=824e4f273923bc52&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.26715,
      "longitude": -97.74306,
      "jobkey": "824e4f273923bc52",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX",
      "formattedRelativeTime": "30+ days ago",
      "stations": ""
    },
    {
      "jobtitle": "Java Manager (Remote)",
      "company": "Indeed",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Indeed",
      "date": "Fri, 18 May 2018 17:06:09 GMT",
      "snippet": "5+ years industry experience in <b>Java</b>. As the world’s number 1 job site, our mission is to help people get jobs....",
      "url": "http://www.indeed.com/viewjob?jk=99e76d8f7dd0699b&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.362755,
      "longitude": -97.792854,
      "jobkey": "99e76d8f7dd0699b",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX 78731",
      "formattedRelativeTime": "24 days ago",
      "stations": ""
    },
    {
      "jobtitle": "JAVA ENGINEER",
      "company": "Carma Carpooling",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Carma Carpooling",
      "date": "Wed, 06 Jun 2018 08:22:59 GMT",
      "snippet": "3+ years <b>Java</b> / JEE development experience. We are looking for a talented <b>java</b> engineer to join our growing team....",
      "url": "http://www.indeed.com/viewjob?jk=889bce38e07a07b2&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.26715,
      "longitude": -97.74306,
      "jobkey": "889bce38e07a07b2",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX",
      "formattedRelativeTime": "5 days ago",
      "stations": ""
    },
    {
      "jobtitle": "Jr Software Engineer - Java",
      "company": "Ping Identity",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Ping Identity",
      "date": "Mon, 16 Apr 2018 06:51:56 GMT",
      "snippet": "Must have <b>Java</b> experience. Experience with multi-threaded programming in <b>Java</b>. At Ping Identity, we're changing the way people think about enterprise security...",
      "url": "http://www.indeed.com/viewjob?jk=49d66e23b0d82c2e&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.415054,
      "longitude": -97.797134,
      "jobkey": "49d66e23b0d82c2e",
      "sponsored": false,
      "expired": false,
      "indeedApply": false,
      "formattedLocationFull": "Austin, TX 78750",
      "formattedRelativeTime": "30+ days ago",
      "stations": ""
    },
    {
      "jobtitle": "J2EE / Java Developer (Remote Opportunity)",
      "company": "Applied Memetics LLC",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Applied Memetics LLC",
      "date": "Mon, 16 Apr 2018 21:52:06 GMT",
      "snippet": "Responsibilities of the J2EE / <b>Java</b> Developer:. The Contracted J2EE / <b>Java</b> Developer shall support mobile health applications by providing maintenance...",
      "url": "http://www.indeed.com/viewjob?jk=791f17e13c8bd576&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.26715,
      "longitude": -97.74306,
      "jobkey": "791f17e13c8bd576",
      "sponsored": false,
      "expired": false,
      "indeedApply": false,
      "formattedLocationFull": "Austin, TX",
      "formattedRelativeTime": "30+ days ago",
      "stations": ""
    },
    {
      "jobtitle": "Java JSF Developer",
      "company": "GeekSI",
      "city": "Austin",
      "state": "TX",
      "country": "US",
      "language": "en",
      "formattedLocation": "Austin, TX",
      "source": "Indeed",
      "date": "Sun, 10 Jun 2018 20:28:27 GMT",
      "snippet": "<b>Java</b> server faces:. 2+ years’ experience with <b>Java</b> application development. 1 year experience programming in <b>Java</b> Server Faces 2.2 /or 2.3 (fluent....",
      "url": "http://www.indeed.com/viewjob?jk=dafaee0d807e1b4b&qd=-_Qc7tmHzAfyozhKO6SDoogsRUmGFvIltONpcOOmB5ARdIPXjia8Il1dvSZwyXqe3xI8SPZP5inIrO3sKKX2LMLidg4dRPmbrZKkQ7da8IY&indpubnum=3656006034426299&atk=1cfolnf0i5sohc3t",
      "onmousedown": "indeed_clk(this,'1056');",
      "latitude": 30.26715,
      "longitude": -97.74306,
      "jobkey": "dafaee0d807e1b4b",
      "sponsored": false,
      "expired": false,
      "indeedApply": true,
      "formattedLocationFull": "Austin, TX",
      "formattedRelativeTime": "1 day ago",
      "stations": ""
    }
  ]
}
